### ISSUE TITLE
When running set.js ik keeps looping

### ISSUE THREAD

**Issue by mirjamblekkenhorst** [ibmtjbot/tjbot#155]
I have set up the raspberry PI from the TJBOT package but faced many issues.
I have first installed the latest raspberry version and seems that the latest node.js version is v10

Installing Tjbot curl -sL http://ibm.biz/tjbot-bootstrap | sudo sh - seems to work fine

but then when installing the code it seems to go wrong.
npm does not seem to be running with node v10 and I have filled my credentials for the cloud services but I think I might have gone wrong here swell.

I do not fully understand the instructions for the credentials
and filled the API Key by copy from the manage service page and same for the url
when I have changed this in the config file I am not sure if I need to save this or can simply close the terminal?
And then running stt.js it keeps looping... anybody who can help me with the set up?

**Comment by jweisz** [comment]
> npm does not seem to be running with node v10

Did you have any errors when you did `npm install`?

For reference, these are the version of `npm` and `node` running on my tjbot:

```
$ npm --version
5.8.0
$ node --version
v10.15.2
```

> when I have changed this in the config file I am not sure if I need to save this or can simply close the terminal?

Yes, you need to save your credentials in the `config.js` file before closing the terminal.

> And then running stt.js it keeps looping

Looping is desired behavior. The script runs until you kill it (ctrl-c), and it opens the microphone so you can speak commands to TJBot.

Closing this issue since I have answered your questions, but please re-open if you have further difficulties.
