### ISSUE TITLE
Update documentation on IBM Cloud services

### ISSUE THREAD

**Issue by heather-fillerup-miller** [ibmtjbot/tjbot#199]
Track all document updates needed in this issue

**Comment by heather-fillerup-miller** [comment]
Update IBM cloud credential/authentication instructions- currently found under left nav bar "Manage" -> "Credentials" -> Download

**Comment by heather-fillerup-miller** [comment]
Update Neopixel instructions for Raspberry Pi 4 Fix from issue #211

**Comment by ljmwaugh** [comment]
initial draft of updating the Cloud Services documentation
[Watson Services in IBM Cloud v3.docx](https://github.com/ibmtjbot/tjbot/files/10415863/Watson.Services.in.IBM.Cloud.v3.docx)

**Comment by jweisz** [comment]
Need to add instructions for downloading credentials instead of just copy/paste. Then the plan will be:

- [ ] 1. Convert the word doc to markdown
- [ ] 2. Commit the markdown (+ images) to a new `tjbot/docs` folder
- [ ] 3. For each recipe, update the credential instructions to point to the new credential instructions in the `docs` folder (and take you to the right anchored section)
- [ ] 4. For bootstrap's README, also just point to the new credential instructions

**Comment by jweisz** [comment]
We decided to move this info to the wiki, so closing this issue.
