### ISSUE TITLE
Servo arm too far recessed => arm falls off

### ISSUE THREAD

**Issue by tobykurien** [ibmtjbot/tjbot#5]
The Servo arm is recessed too far and so it doesn't clip well into the servo motor. This leads to the arm falling off easily. 
![img_0014](https://cloud.githubusercontent.com/assets/972315/20618608/c66a6274-b2f8-11e6-99aa-1faf776d324a.JPG)

**Comment by tobykurien** [comment]
PS: The screw to hold it together was quite short

**Comment by victordibia** [comment]
I'll look into this later when I have our 3D printed TJ handy. I'll update you on what I find.
Thanks for noting this.
-V.

**Comment by aarrccooxx** [comment]
hi Toby,
we intentionally designed the fit to be like this so that the arm would not sag.  And your parts fit looks like mine. I think we have to use the screw to keep the arm attached, press fit will not be enough.

 Does your screw look like mine?   thanks

![img_5538](https://cloud.githubusercontent.com/assets/24227351/20716277/4afb0874-b617-11e6-9a73-4c7c54cf9c8c.JPG)

![img_5539](https://cloud.githubusercontent.com/assets/24227351/20716294/54882d2c-b617-11e6-8485-fbb1235e2f58.JPG)

![img_5543](https://cloud.githubusercontent.com/assets/24227351/20716331/74308548-b617-11e6-9627-36fd1c748193.JPG)

![img_5544](https://cloud.githubusercontent.com/assets/24227351/20716341/7f86620a-b617-11e6-819f-b3e32a67a830.JPG)

**Comment by tobykurien** [comment]
Yep looks similar to mine

**Comment by aarrccooxx** [comment]
Great, can you try your screw again please?  It's also possible that your servo is recessed too far into the body.  Check that the bottom mounting ears on the servo are fitting into the mating slot on the floor of the jaw plate.

<img width="630" alt="servo slot" src="https://cloud.githubusercontent.com/assets/24227351/20717028/c060cd4a-b619-11e6-8bda-ea3dec66f8a9.png">

<img width="604" alt="servo slot 2" src="https://cloud.githubusercontent.com/assets/24227351/20717033/c57c2c48-b619-11e6-81b1-12a3b40a5f34.png">

**Comment by tobykurien** [comment]
Aha! I get it now - the arm needs to be recessed so that it isn't loose when the servo is screwed in. Makes sense after full assembly :-) Closing this issue.
