### ISSUE TITLE
LED is not changing color

### ISSUE THREAD

**Issue by playground** [ibmtjbot/tjbot#52]
I can speak to it and the response comes back correctly displayed in the console but the LED will always shows light blue.

**Comment by victordibia** [comment]
Hi @playground 

If you have not color response at all on your LED, its possible that you may have it incorrectly connected. Please revisit the wiring diagram we provide. In some cases, an incorrectly connected LED may damage it, in which case it is suggested you try a new LED.

On the other hand, if you have incorrect colors, this may be due to a known conflict between the LED on the board and audio module. To address this .. see the notes on step 13 here .. https://github.com/ibmtjbot/tjbot/tree/master/bootstrap
